=== joan-cb/schema-stream/outputSchema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "properties": {
        "name": {
            "type": "string"
        },
        "age": {
            "type": "number"
        },
        "city": {
            "type": "string"
        },
        "email": {
            "type": "string"
        },
        "phone": {
            "type": "string"
        },
        "anArray": {
            "items": {
                "type": "number"
            },
            "type": "array"
        },
        "address": {
            "properties": {
                "street": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "zip": {
                    "type": "string"
                }
            },
            "additionalProperties": false,
            "type": "object",
            "required": [
                "street",
                "city",
                "state",
                "zip"
            ]
        },
        "orders": {
            "items": true,
            "type": "array"
        },
        "isActive": {
            "type": "boolean"
        },
        "lastLogin": {
            "type": "string"
        }
    },
    "additionalProperties": false,
    "type": "object",
    "required": [
        "name",
        "age",
        "city",
        "email",
        "phone",
        "isActive",
        "lastLogin"
    ]
}

=== joan-cb/schema-stream/test.json
{
    "name": "John",
    "age": 30,
    "city": "New York",
    "email": "john@example.com",
    "phone": "+1234567890",
    "anArray": [1, 2, 3, 4, 5],
    "address": {
        "street": "123 Main St",
        "city": "Anytown",
        "state": "CA",
        "zip": "12345"
    },
    "orders": [
        {
            "orderId": 1,
            "product": "Widget",
            "quantity": 2,
            "price": 10.00
        },
        {
            "orderId": 2,
            "product": "Gadget",
            "quantity": 1,
            "price": 15.00
        }
    ],
    "isActive": true,
    "lastLogin": "2023-01-15T10:30:00Z"
    
}
